# -*- coding: utf-8 -*-
"""TrabalhoSelenium_Grupo1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nPiKTrYmTkjpBsTy77Vv0AooDIM0nnbQ
"""

#Instalando o Seleniumbase e pandas
!pip install seleniumbase

#Instalando o Chromium no Colab pois é necessário para a extração do robô
!wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
!echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
!apt-get update
!apt-get install -y google-chrome-stable

#Importando as bibliotecas
import json
from seleniumbase import SB
from selenium.webdriver.common.by import By

# |Constantes e função de login|
URL_SITE = "https://www.saucedemo.com/"
USERNAME = "standard_user"
PASSWORD = "secret_sauce"

CHECKOUT = {
    "first_name": "Trainee",
    "last_name": "PiJunior",
    "zip_code": "31270-901"
}

def realizarLogin(sb: SB):
    #A função automatiza o login no site e recebe o 'sb'para controle do navegador
    print("Iniciando...")
    #Abrir a página usando URL_SITE
    sb.open(URL_SITE)

    # |Preenchimento de credenciais|
    sb.type("#user-name", USERNAME)
    sb.type("#password", PASSWORD)
    sb.click("#login-button")

    # |Validação do login|
    sb.wait_for_element("#inventory_container")
    print("Login realizado com sucesso!")

def extrairDadosProdutos(sb: SB) -> list[dict]:
    # Lista para armazenar todos os produtos
    lista_produtos = []

    # Encontrar todos os contêineres de produtos
    elementos_produtos = sb.find_elements("div.inventory_item")

    print(f"Encontrados {len(elementos_produtos)} produtos.")

    # Iterar sobre os elementos e extrair os dados
    for produto_elemento in elementos_produtos:
        try:
            # Extraindo dados
            nome = produto_elemento.find_element(By.CLASS_NAME, "inventory_item_name").text
            descricao = produto_elemento.find_element(By.CLASS_NAME, "inventory_item_desc").text
            preco_texto = produto_elemento.find_element(By.CLASS_NAME, "inventory_item_price").text

            # Limpar o símbolo da moeda e converter para float
            preco_float = float(preco_texto.replace("$", ""))

            # Adicionar ao dicionário
            produto_dict = {
                "nome": nome,
                "descricao": descricao,
                "preco": preco_float
            }
            lista_produtos.append(produto_dict)

        except Exception as e:
            print(f"Erro ao extrair dados de um produto: {e}")
            continue

    print("Extração de dados concluída!")
    return lista_produtos

# Gerar e salvar o arquivo JSON
def salvar_em_json(dados: list[dict], nome_arquivo: str):
    try:
        with open(nome_arquivo, 'w', encoding='utf-8') as f:
            json.dump(dados, f, indent=4, ensure_ascii=False)
        print(f"\nTabela JSON salva com sucesso: {nome_arquivo}")
    except Exception as e:
        print(f"\nErro ao salvar o arquivo JSON: {e}")

# Teste de compilação
def testar_e_imprimir_extracao():

    dados_extraidos = []

    # Inicia o SeleniumBase.
    try:
        with SB(headless=False) as sb:

            # Login
            realizarLogin(sb)

            # Extração de Dados
            dados_extraidos = extrairDadosProdutos(sb)

            # IMPRESSÃO DOS RESULTADOS
            print("Resultado da extração")
            print(f"Total de produtos coletados: {len(dados_extraidos)}")

            if dados_extraidos:
                # O indent=4 torna a estrutura visualmente organizada
                print(json.dumps(dados_extraidos, indent=4, ensure_ascii=False))

                # Salvando a lista de produtos em JSON
                salvar_em_json(dados_extraidos, "produtos_coletados.json")

                print("\nTeste de extração concluído!")
            else:
                print("Falha: lista de produtos está vazia. Verifique a função extrairDadosProdutos.")

    except Exception as e:
        print(f"\nErro fatal durante o teste {e}")

# chamada principal
testar_e_imprimir_extracao()

# Variável para armazenar os dados finais do checkout
dados_finais_compra = []

try:
    with SB(headless=True) as sb:
        realizarLogin(sb)

        # Adiciona todos os produtos ao carrinho
        botoes = sb.find_elements(By.CLASS_NAME, "btn_primary")
        for botao in botoes:
            botao.click()
        print("\nTodos os produtos adicionados ao carrinho.")

        # Abre a página do carrinho
        sb.find_element(By.CLASS_NAME, "shopping_cart_link").click()
        sb.wait_for_element("#cart_contents_container")

        # Conclui o check dos itens
        sb.find_element(By.ID, "checkout").click()
        sb.wait_for_element("#checkout_info_container")

        # Adiciona informações referente ao comprador
        sb.find_element(By.ID, "first-name").send_keys(CHECKOUT["first_name"])
        sb.find_element(By.ID, "last-name").send_keys(CHECKOUT["last_name"])
        sb.find_element(By.ID, "postal-code").send_keys(CHECKOUT["zip_code"])

        # Confirma informações
        sb.find_element(By.ID, "continue").click()
        sb.wait_for_element("#checkout_summary_container")

        # Pega os dados referentes ao pagamento e entrega
        dados_pagamento = sb.find_elements(By.CLASS_NAME, "summary_value_label")
        meio_pagamento = dados_pagamento[0].text
        forma_entrega = dados_pagamento[1].text
        print("Meio de pagamento:", meio_pagamento)
        print("Forma de entrega:", forma_entrega)

        # Raspa o valor total da compra
        valor_total_compra_texto = sb.find_element(By.CLASS_NAME, "summary_total_label").text
        print(f"Valor Total Final: {valor_total_compra_texto}")

        #Finaliza a compra
        sb.find_element(By.ID, "finish").click()

        #Verifica se a compra foi concluída com sucesso
        sb.wait_for_element("#checkout_complete_container")

        #Raspa a mensagem de confirmação
        mensagem_sucesso = sb.find_element(By.CLASS_NAME, "complete-text").text

        if mensagem_sucesso:
            print("Compra finalizada!")
            print("Mensagem de Confirmação:", mensagem_sucesso)

            # Adiciona os dados do checkout à lista
            dados_finais_compra.append({
                "status_compra": "Concluída com Sucesso",
                "meio_pagamento": meio_pagamento,
                "forma_entrega": forma_entrega,
                "valor_total": valor_total_compra_texto,
                "mensagem_confirmacao": mensagem_sucesso
            })
        else:
            print("Erro ao finalizar a compra")

        # Chamada para gerar o segundo arquivo .json
        if dados_finais_compra:
            salvar_em_json(dados_finais_compra, "info_compra.json")

except Exception as e:
    print(f"\nErro ao tentar realizar a compra no bloco principal: {e}")